var data = [
	{
		id: 1,
		name: "Kayak",
		category: "Watersports",
		description: "A boat for one person",
		price: 275,
	},
	{
		id: 2,
		name: "Lifejacket",
		category: "Watersports",
		description: "Protective and fashionable",
		price: 48.95,
	},
	{
		id: 3,
		name: "Soccer Ball",
		category: "Soccer",
		description: "FIFA-approved size and weight",
		price: 19.5,
	},
	{
		id: 4,
		name: "Corner Flags",
		category: "Soccer",
		description: "Give your playing field a professional touch",
		price: 34.95,
	},
	{
		id: 5,
		name: "Stadium",
		category: "Soccer",
		description: "Flat-packed 35,000-seat stadium",
		price: 77,
	},
	{
		id: 6,
		name: "Thinking Cap",
		category: "Chess",
		description: "Improve brain efficiency by 75%",
		price: 16,
	},
	{
		id: 7,
		name: "Unsteady Chair",
		category: "Chess",
		description: "Secretly give your opponent a disadvantage",
		price: 29.95,
	},
	{
		id: 8,
		name: "Human Chess Board",
		category: "Chess",
		description: "A fun game for the family",
		price: 75,
	},
	{
		id: 9,
		name: "Bling Bling King",
		category: "Chess",
		description: "Gold-plated, diamond-studded King",
		price: 789,
	},
	{
		id: 10,
		name: "Kayak",
		category: "Watersports",
		description: "A boat for one person",
		price: 275,
	},
	{
		id: 11,
		name: "Lifejacket",
		category: "Watersports",
		description: "Protective and fashionable",
		price: 48.95,
	},
	{
		id: 12,
		name: "Soccer Ball",
		category: "Soccer",
		description: "FIFA-approved size and weight",
		price: 19.5,
	},
	{
		id: 13,
		name: "Corner Flags",
		category: "Soccer",
		description: "Give your playing field a professional touch",
		price: 34.95,
	},
	{
		id: 14,
		name: "Stadium",
		category: "Soccer",
		description: "Flat-packed 35,000-seat stadium",
		price: 989,
	},
	{
		id: 15,
		name: "Thinking Cap",
		category: "Chess",
		description: "Improve brain efficiency by 75%",
		price: 16,
	},
	{
		id: 16,
		name: "Unsteady Chair",
		category: "Chess",
		description: "Secretly give your opponent a disadvantage",
		price: 29.95,
	},
	{
		id: 17,
		name: "Human Chess Board",
		category: "Chess",
		description: "A fun game for the family",
		price: 75,
	},
	{
		id: 18,
		name: "Bling Bling King",
		category: "Chess",
		description: "Gold-plated, diamond-studded King",
		price: 234,
	},
	{
		id: 19,
		name: "Kayak",
		category: "Watersports",
		description: "A boat for one person",
		price: 275,
	},
	{
		id: 20,
		name: "Lifejacket",
		category: "Watersports",
		description: "Protective and fashionable",
		price: 48.95,
	},
	{
		id: 21,
		name: "Soccer Ball",
		category: "Soccer",
		description: "FIFA-approved size and weight",
		price: 19.5,
	},
	{
		id: 22,
		name: "Corner Flags",
		category: "Soccer",
		description: "Give your playing field a professional touch",
		price: 34.95,
	},
	{
		id: 23,
		name: "Stadium",
		category: "Soccer",
		description: "Flat-packed 35,000-seat stadium",
		price: 444,
	},
	{
		id: 24,
		name: "Thinking Cap",
		category: "Chess",
		description: "Improve brain efficiency by 75%",
		price: 16,
	},
	{
		id: 25,
		name: "Unsteady Chair",
		category: "Chess",
		description: "Secretly give your opponent a disadvantage",
		price: 29.95,
	},
	{
		id: 26,
		name: "Human Chess Board",
		category: "Chess",
		description: "A fun game for the family",
		price: 75,
	},
	{
		id: 27,
		name: "Bling Bling King",
		category: "Chess",
		description: "Gold-plated, diamond-studded King",
		price: 1200,
	},
];
module.exports = function() {
	return {
		products: data,
		categories: [...new Set(data.map((p) => p.category))].sort(),
		orders: [],
	};
};
